/**
 * AUTH SERVICES
 */
export const AUTH_SERVICE = 'AUTH_SERVICE';
export const AUTH_LOGIN = 'AUTH_LOGIN';

/**
 *  EMPLOYE SERVICES
 */
export const EMPLOYEE_SERVICE = 'EMPLOYEE_SERVICE';
export const GET_EMPLOYEE_BY_ID = 'GET_EMPLOYEE_BY_ID';
export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';

/**
 *  ATTENDANCE SERVICES
 */
export const ATTENDANCE_SERVICE = 'ATTENDANCE_SERVICE';
export const ATTENDANCE_CHECKIN = 'ATTENDANCE_CHEKCIN';
export const ATTENDANCE_RECENT = 'ATTENDANCE_RECENT';
export const ATTENDANCE_LIST = 'ATTENDANCE_LIST';
